#!/bin/sh

case "$1" in 
    start)
        echo "Staring aesdsocket"
        start-stop-daemon -S -n aesdsocket -d /usr/bin/aesdsocket
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K -n aesdsocket
        ;;
    *)
        echo "Usage: {start|stop}
    exit 1
esac

exit 0